# -*- coding: utf-8 -*-
"""Rekoemendasi_Budaya.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmMSDymuWiXWoNByIfXxi7BiqpL4jg4d
"""
import pandas as pd
from flask import Flask, jsonify, request
from flask_cors import CORS

app = Flask(__name__)
CORS(app)
df = pd.read_csv("budaya_jawa_r.csv")
df["Budaya"] = df["Budaya"].str.strip().str.lower()
df["Kota"] = df["Kota"].str.strip().str.lower()

# Ambil yang rating-nya paling tinggi dari duplikat nama tempat dan kota
df = df.sort_values("Rating", ascending=False)
df = df.drop_duplicates(subset=["Budaya", "Kota"], keep="first")
df.drop_duplicates(inplace=True)

def rekomendasi_populer(df, top_n=50, kota_pilihan=None):
    # Hitung skor popularitas
    bobot_rating = 0.7
    df["skor_popularitas"] = df["Rating"] * bobot_rating

    # Filter berdasarkan kota jika diberikan
    if kota_pilihan:
       df = df[df["Kota"].astype(str) == str(kota_pilihan)]

    df["Kota"] = df["Kota"].str.strip()

    # Urutkan berdasarkan skor popularitas
    df_sorted = df.sort_values(by="skor_popularitas", ascending=False)

    # Ambil top N tempat wisata
    top_wisata = df_sorted.head(top_n)

    # Pilih kolom yang akan ditampilkan
    rekomendasi = top_wisata[["Budaya", "Kota", "Jenis", "Rating", "Deskripsi"]]

    return rekomendasi
    
@app.route('/budaya', methods=['GET'])
def get_rekomendasi_wisata():
    file_path = "budaya_jawa.csv"
    kota_pilihan = None
    rekomendasi = rekomendasi_populer(df, top_n=500, kota_pilihan=kota_pilihan)
    return jsonify(rekomendasi.to_dict(orient='records'))


if __name__ == "__main__":
   app.run()
